"""assignment eta snapshot

Revision ID: 0591e6c69d50
Revises: ca0c24ea2536
Create Date: 2026-08-27 16:23:25.763270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0591e6c69d50'
down_revision: Union[str, None] = 'ca0c24ea2536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing rows have no value, so NOT NULL cannot be applied directly.
    # 1) Add the column as nullable
    op.add_column("assignments", sa.Column("eta", sa.DateTime(timezone=True), nullable=True))
    # 2) Backfill past assignments from each ship's ETA (the best value available)
    op.execute(
        """
        UPDATE assignments a
        SET eta = s.eta
        FROM ships s
        WHERE a.ship_id = s.id AND a.eta IS NULL
        """
    )
    # 3) No empty rows remain; enforce the constraint
    op.alter_column("assignments", "eta", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'eta')
    # ### end Alembic commands ###
