"""allow deleting ships and berths, mark plans stale

Revision ID: 71d8092b8860
Revises: 0591e6c69d50
Create Date: 2026-08-27 23:06:26.963392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '71d8092b8860'
down_revision: Union[str, None] = '0591e6c69d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) Name copies: add nullable first, existing rows have no value yet.
    op.add_column("assignments", sa.Column("ship_name", sa.String(length=120), nullable=True))
    op.add_column("assignments", sa.Column("berth_name", sa.String(length=120), nullable=True))
    op.add_column("unassigned_entries", sa.Column("ship_name", sa.String(length=120), nullable=True))

    # 2) Backfill from the rows they still point at.
    op.execute(
        """
        UPDATE assignments a
        SET ship_name = s.name
        FROM ships s
        WHERE a.ship_id = s.id AND a.ship_name IS NULL
        """
    )
    op.execute(
        """
        UPDATE assignments a
        SET berth_name = b.name
        FROM berths b
        WHERE a.berth_id = b.id AND a.berth_name IS NULL
        """
    )
    op.execute(
        """
        UPDATE unassigned_entries u
        SET ship_name = s.name
        FROM ships s
        WHERE u.ship_id = s.id AND u.ship_name IS NULL
        """
    )
    # Anything still empty had no row to read from; leave a placeholder rather
    # than blocking the migration.
    op.execute("UPDATE assignments SET ship_name = '' WHERE ship_name IS NULL")
    op.execute("UPDATE assignments SET berth_name = '' WHERE berth_name IS NULL")
    op.execute("UPDATE unassigned_entries SET ship_name = '' WHERE ship_name IS NULL")

    # 3) Now the constraint can be enforced.
    op.alter_column("assignments", "ship_name", nullable=False)
    op.alter_column("assignments", "berth_name", nullable=False)
    op.alter_column("unassigned_entries", "ship_name", nullable=False)

    # 4) Let ships and berths be deleted: the reference goes null, the row stays.
    op.alter_column("assignments", "ship_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("assignments", "berth_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("unassigned_entries", "ship_id", existing_type=sa.INTEGER(), nullable=True)

    op.drop_constraint(op.f("assignments_ship_id_fkey"), "assignments", type_="foreignkey")
    op.drop_constraint(op.f("assignments_berth_id_fkey"), "assignments", type_="foreignkey")
    op.drop_constraint(
        op.f("unassigned_entries_ship_id_fkey"), "unassigned_entries", type_="foreignkey"
    )
    op.create_foreign_key(
        "assignments_ship_id_fkey", "assignments", "ships", ["ship_id"], ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "assignments_berth_id_fkey", "assignments", "berths", ["berth_id"], ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "unassigned_entries_ship_id_fkey", "unassigned_entries", "ships", ["ship_id"], ["id"],
        ondelete="SET NULL",
    )

    # 5) Staleness marker on the plan itself.
    op.add_column("plans", sa.Column("stale_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("plans", sa.Column("stale_reason", sa.String(length=200), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unassigned_entries', type_='foreignkey')
    op.create_foreign_key(op.f('unassigned_entries_ship_id_fkey'), 'unassigned_entries', 'ships', ['ship_id'], ['id'])
    op.alter_column('unassigned_entries', 'ship_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('unassigned_entries', 'ship_name')
    op.drop_column('plans', 'stale_reason')
    op.drop_column('plans', 'stale_at')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_berth_id_fkey'), 'assignments', 'berths', ['berth_id'], ['id'])
    op.create_foreign_key(op.f('assignments_ship_id_fkey'), 'assignments', 'ships', ['ship_id'], ['id'])
    op.alter_column('assignments', 'berth_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assignments', 'ship_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('assignments', 'berth_name')
    op.drop_column('assignments', 'ship_name')
    # ### end Alembic commands ###
